"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Template = { id?: string; garage_name: string; service_name: string; price: number; duration_minutes: number; description: string; };
const SERVICE_OPTIONS = ["Oil Change","MOT Test","General Service","Full Service","Brake Pads - Front","Brake Pads - Rear","Brake Discs","Tyre Change / Fitting","Puncture Repair","Diagnostics","Engine Repair","Clutch Repair","Battery Replacement","Air Con Regas","Exhaust Repair","Suspension Repair","Timing Belt","Other - Custom"];
export default function PriceTemplatesPage() {
  const [templates, setTemplates] = useState<Template[]>([]); const [loading, setLoading] = useState(true); const [selectedService, setSelectedService] = useState(""); const [customService, setCustomService] = useState(""); const [newService, setNewService] = useState({ price: 0, duration_minutes: 60, description: "" });
  const fetchTemplates = async () => { setLoading(true); const { data } = await supabase.from("garage_price_templates").select("*").eq("garage_name", "haji auto center").order("service_name"); if (data) setTemplates(data); setLoading(false); };
  useEffect(() => { fetchTemplates(); }, []);
  const getFinalServiceName = () => { if (selectedService === "Other - Custom") return customService; return selectedService; };
  const addTemplate = async () => { const finalName = getFinalServiceName(); if (!finalName || !newService.price) { alert("Service select karo aur price dalo!"); return; } const { error } = await supabase.from("garage_price_templates").insert({ garage_name: "haji auto center", service_name: finalName, price: newService.price, duration_minutes: newService.duration_minutes, description: newService.description }); if (error) { alert(error.message); return; } setSelectedService(""); setCustomService(""); setNewService({ price: 0, duration_minutes: 60, description: "" }); fetchTemplates(); };
  const deleteTemplate = async (id: string) => { if (!confirm("Delete?")) return; await supabase.from("garage_price_templates").delete().eq("id", id); fetchTemplates(); };
  return (
    <div className="min-h-screen bg-black text-white p-4 md:p-8"><div className="max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-8"><div><h1 className="text-2xl font-bold">haji auto center</h1><p className="text-yellow-400 text-sm font-bold">Price Templates - AI System</p><p className="text-zinc-500 text-xs mt-1">Garage khud apni marzi ki price set karega - Customer ko homepage pe dikhega</p></div><a href="/garage" className="px-4 py-2 bg-zinc-800 rounded-xl text-sm">← Garage Dashboard</a></div>
      <div className="bg-zinc-900 rounded-2xl p-6 border border-yellow-400/20 mb-8"><h2 className="font-bold text-yellow-400 mb-4">+ Add New Service Price (Dropdown)</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><select value={selectedService} onChange={e=>setSelectedService(e.target.value)} className="bg-black border border-zinc-700 rounded-xl px-4 py-3 text-sm"><option value="">-- Select Service --</option>{SERVICE_OPTIONS.map(s=><option key={s} value={s}>{s}</option>)}</select><input type="number" value={newService.price} onChange={e=>setNewService({...newService, price: parseFloat(e.target.value)||0})} placeholder="Price £" className="bg-black border border-zinc-700 rounded-xl px-4 py-3 text-sm" /><input type="number" value={newService.duration_minutes} onChange={e=>setNewService({...newService, duration_minutes: parseInt(e.target.value)||60})} placeholder="Time Mins" className="bg-black border border-zinc-700 rounded-xl px-4 py-3 text-sm" /></div>{selectedService === "Other - Custom" && (<input value={customService} onChange={e=>setCustomService(e.target.value)} placeholder="Custom Service Naam Likho (e.g. Hybrid Battery Repair)" className="w-full mt-3 bg-black border border-yellow-400/50 rounded-xl px-4 py-3 text-sm" />)}<input value={newService.description} onChange={e=>setNewService({...newService, description: e.target.value})} placeholder="Description" className="w-full mt-3 bg-black border border-zinc-700 rounded-xl px-4 py-3 text-sm" /><button onClick={addTemplate} className="mt-4 w-full md:w-auto px-8 py-3 bg-yellow-400 text-black rounded-xl font-bold">Add Price Template</button><p className="text-xs text-zinc-500 mt-2">💡 Garage jo price yahan set karega, wo customer ko homepage garage card pe aur booking time auto show hoga</p></div>
      {loading ? <p className="text-zinc-500">Loading...</p> : (<div className="space-y-3"><h3 className="font-bold text-sm text-zinc-400">Your Current Prices (Customer ko yahi dikhenge):</h3>{templates.map(t=>(<div key={t.id} className="bg-zinc-900 rounded-xl p-4 border border-zinc-800 flex justify-between items-center"><div><p className="font-bold">{t.service_name}</p><p className="text-xs text-zinc-500">{t.description} • {t.duration_minutes} mins • <span className="text-yellow-400">£{t.price}</span></p></div><button onClick={()=>deleteTemplate(t.id!)} className="w-8 h-8 bg-red-500/20 text-red-400 rounded-full text-xs">✕</button></div>))}{templates.length===0 && <p className="text-zinc-500 text-sm">No prices yet - Upar se dropdown se select karke add karo</p>}</div>)}
    </div></div>
  );
}
