"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function TrackPage() {
  const params = useParams(); const ref = params.ref as string;
  const [booking, setBooking] = useState<any>(null); const [garage, setGarage] = useState<any>(null);
  const [loading, setLoading] = useState(true); const [payMethod, setPayMethod] = useState<"cash" | "card">("card");
  useEffect(() => { const fetchData = async () => { const { data: b } = await supabase.from("bookings").select("*").eq("booking_ref", ref).single(); if (b) { setBooking(b); const { data: g } = await supabase.from("garages").select("*").eq("id", b.garage_id).single(); if (g) setGarage(g); } setLoading(false); }; fetchData(); }, [ref]);
  const steps = [{ id: "CONFIRMED", label: "Booking Confirmed" }, { id: "IN_PROGRESS", label: "Work In Progress" }, { id: "READY", label: "Ready for Collection" }, { id: "COMPLETED", label: "Completed" }];
  const currentIndex = steps.findIndex(s => s.id === booking?.status); const isFuture = (idx: number) => idx > currentIndex; const isCurrent = (idx: number) => idx === currentIndex;
  const handlePay = async () => {
    if (payMethod === "cash") { alert(`Please pay £${booking?.total_price?.toFixed(2)} in cash at haji auto center.\nRef: ${ref}`); }
    else { alert(`Redirecting to Stripe for £${booking?.total_price?.toFixed(2)}...`); }
    await supabase.from("bookings").update({ payment_method: payMethod }).eq("booking_ref", ref);
  };
  const downloadInvoice = () => {
    const win = window.open("", "_blank"); if (!win) return;
    const servicesHtml = (booking.services || []).map((s:any) => `<tr><td>${s.name}</td><td>£${s.price.toFixed(2)}</td></tr>`).join("");
    const partsHtml = (booking.parts || []).map((p:any) => `<tr><td>${p.name} x${p.qty}</td><td>£${(p.price * p.qty).toFixed(2)}</td></tr>`).join("");
    win.document.write(`<html><head><title>Invoice ${ref}</title><style>body{font-family:Arial;padding:40px} table{width:100%;border-collapse:collapse;margin-top:20px} th,td{border:1px solid #ddd;padding:10px} th{background:#000;color:#fff}.total{font-weight:bold;font-size:18px;background:#ffeb3b}</style></head><body><h1>haji auto center</h1><p>G40 1EU • Invoice: ${ref}</p><p>Customer: ${booking.customer_name} | Phone: ${booking.phone} | Car: ${booking.car_reg}</p><h3>Services</h3><table><tr><th>Service</th><th>Price</th></tr>${servicesHtml}</table><h3>Parts</h3><table><tr><th>Part</th><th>Price</th></tr>${partsHtml}</table><table><tr><td>Labour (${booking.labour_hours}h x £${booking.labour_rate})</td><td>£${((booking.labour_hours||0)*(booking.labour_rate||0)).toFixed(2)}</td></tr>${booking.taxi_required?`<tr><td>Taxi</td><td>£${booking.taxi_cost}</td></tr>`:""}<tr><td>Subtotal</td><td>£${booking.subtotal}</td></tr><tr><td>VAT 20%</td><td>£${booking.vat}</td></tr><tr class="total"><td>Total</td><td>£${booking.total_price}</td></tr></table></body></html>`);
    win.document.close(); win.print();
  };
  if (loading) return <div className="min-h-screen bg-black text-white grid place-items-center">Loading {ref}...</div>;
  if (!booking) return <div className="min-h-screen bg-black text-white grid place-items-center">Booking not found: {ref}</div>;
  return (
    <div className="min-h-screen bg-zinc-950 text-white"><main className="max-w-xl mx-auto p-4 md:p-6">
      <div className="bg-black rounded-2xl p-6 border border-zinc-800"><div className="flex justify-between items-start"><div><h1 className="text-xl font-bold">{garage?.name || "haji auto center"}</h1><p className="text-xs text-zinc-500">{garage?.address || "G40 1EU"} • Ref: {booking.booking_ref} • {booking.car_reg}</p></div><span className={`px-3 py-1 rounded-full text-xs font-bold ${booking.status === "READY"? "bg-green-500" : booking.status === "IN_PROGRESS"? "bg-yellow-400 text-black" : "bg-zinc-700"}`}>{booking.status}</span></div>
      <div className="mt-6 space-y-3">{steps.map((step, idx) => (<div key={step.id} className={`flex gap-3 items-center ${isFuture(idx)? "opacity-30" : ""}`}><div className={`w-8 h-8 rounded-full grid place-items-center text-sm font-bold ${isCurrent(idx)? "bg-yellow-400 text-black" : idx < currentIndex? "bg-green-500" : "bg-zinc-800"}`}>{idx < currentIndex? "✓" : idx+1}</div><div><p className={`font-semibold text-sm ${isCurrent(idx)? "text-[#fac51c]" : ""}`}>{step.label}</p><p className="text-xs text-zinc-500">{idx===0?`Drop-off: ${booking.drop_off_date} at ${booking.drop_off_time}`:idx===1?"Mechanic working":idx===2?"Ready - please collect":"Thank you!"}</p></div></div>))}</div></div>
      {booking.total_price && booking.total_price > 0? (<div className="bg-white text-black rounded-2xl p-6 mt-6"><div className="flex justify-between items-center"><h2 className="text-lg font-bold">Invoice - {booking.booking_ref}</h2><span className={`px-3 py-1 rounded-full text-xs font-bold ${booking.payment_status === 'paid'? 'bg-green-500 text-white' : 'bg-yellow-400 text-black'}`}>{(booking.payment_status || 'unpaid').toUpperCase()}</span></div>
      <div className="mt-4 space-y-4 text-sm">{booking.services?.length>0 && <div><p className="font-bold">Services</p>{booking.services.map((s:any,i:number)=><div key={i} className="flex justify-between py-1 border-b"><span>{s.name}</span><span>£{s.price.toFixed(2)}</span></div>)}</div>}{booking.parts?.length>0 && <div><p className="font-bold">Parts</p>{booking.parts.map((p:any,i:number)=><div key={i} className="flex justify-between py-1 border-b"><span>{p.name} x{p.qty}</span><span>£{(p.price*p.qty).toFixed(2)}</span></div>)}</div>}<div className="bg-zinc-50 rounded-xl p-3 space-y-1"><div className="flex justify-between"><span>Labour ({booking.labour_hours}h x £{booking.labour_rate})</span><span>£{((booking.labour_hours||0)*(booking.labour_rate||0)).toFixed(2)}</span></div>{booking.taxi_required && <div className="flex justify-between"><span>Taxi</span><span>£{booking.taxi_cost?.toFixed(2)}</span></div>}<div className="flex justify-between text-zinc-500"><span>Subtotal</span><span>£{booking.subtotal?.toFixed(2)}</span></div><div className="flex justify-between text-zinc-500"><span>VAT 20%</span><span>£{booking.vat?.toFixed(2)}</span></div><div className="flex justify-between font-bold text-base pt-2 border-t"><span>Total</span><span>£{booking.total_price?.toFixed(2)}</span></div></div></div>
      {booking.payment_status!== 'paid' && (<div className="mt-6"><p className="font-bold text-sm mb-2">Choose Payment:</p><div className="flex gap-2"><button onClick={()=>setPayMethod("cash")} className={`flex-1 py-3 rounded-xl border-2 font-bold ${payMethod==="cash"?"bg-black text-white border-black":"bg-white border-zinc-200"}`}>Cash at Garage</button><button onClick={()=>setPayMethod("card")} className={`flex-1 py-3 rounded-xl border-2 font-bold ${payMethod==="card"?"bg-black text-white border-black":"bg-white border-zinc-200"}`}>Card Online</button></div><button onClick={handlePay} className="w-full mt-3 py-4 bg-yellow-400 rounded-xl font-bold text-lg">Pay £{booking.total_price?.toFixed(2)} - {payMethod === "cash"? "Confirm Cash" : "Pay by Card"}</button></div>)}
      <button onClick={downloadInvoice} className="w-full mt-3 py-3 bg-black text-white rounded-xl text-sm font-bold">Download Invoice PDF</button></div>) : (<div className="bg-zinc-900 rounded-2xl p-6 mt-6 border border-zinc-800 text-center"><p className="text-2xl">💰</p><p className="text-sm font-bold mt-2">Price will be added after inspection</p><p className="text-xs text-zinc-500 mt-1">You will get SMS when invoice is ready.</p></div>)}
      <div className="mt-6 grid grid-cols-2 gap-3"><a href={`tel:${garage?.phone || '0990123456'}`} className="h-12 rounded-full bg-white text-black font-bold grid place-items-center text-sm">Call Garage</a><a href={`https://wa.me/${(garage?.phone || '0990123456').replace(/\D/g,'')}?text=Hi, my booking ref is ${booking.booking_ref} for ${booking.car_reg}`} target="_blank" className="h-12 rounded-full bg-green-600 text-white font-bold grid place-items-center text-sm">WhatsApp</a></div>
    </main></div>
  );
}
